### PR TITLE
Fixes the case spelling of GitHub

### PR DESCRIPTION
**Pull request by dietmarw**
New attempt for  the failed #17.

### CODE REVIEW

**Comment by casella** [comment]
@dietmarw why is this always reported as out-of-date with the base branch?

Should I do update with rebase?

**Comment by casella** [comment]
> @casella Very simple, some other changes have been done since I created this PR. Those changes are orthogonal and would not affect this PR. So you can simply merge without rebasing.

I have no option on GitHub to merge without rebasing. I did rebase and now I can either squash and merge or rebase and merge.

**Comment by dietmarw** [comment]
Unless it is really important to retain the history of PR consisting of several commits, I would always go for squash since that does not create an additional merge commit and is just cleaner.

**Comment by casella** [comment]
Et voilà 😃

**Pull request merged**
